export { default as clearSky} from './01d.jpg';
export { default as fewClouds} from './02d.jpg';
export { default as scatteredClouds} from './03d.jpg';
export { default as brokenClouds} from './04d.jpg';
export { default as showerRain} from './09d.jpg';
export { default as rain} from './10d.jpg';
export { default as thunder} from './11d.jpg';
export { default as snow} from './13d.jpg';
export { default as mist} from './50d.jpg';